### ISSUE TITLE
What are offsets? 

### ISSUE THREAD

**Issue by lassemt** [sigal-raab/Motion#2]
Hi Sigal, 
thank you for providing a good solution for exporting BVH from Motion Diffusion Model output. I've been experimenting with it to learn more about the motion format.

In `animation_from_positions` I noticed there is an optional parameter called offsets:
https://github.com/sigal-raab/Motion/blob/3abc6e3e2c20f53f0e682f6bb2b658adb4c13563/InverseKinematics.py#L520
Is this a parameter where I can provide default bone offsets that is used when calculating joint positions to rotations? For example offsets from bones in the default T-pose?

Best regards
Lasse

**Comment by sigal-raab** [comment]
> Is this a parameter where I can provide default bone offsets that is used when calculating joint positions to rotations? For example offsets from bones in the default T-pose?

Yes!

**Comment by lassemt** [comment]
Awesome! And it looks I can use the offsets from existing bvh with BVH.load function. Thank you!
